#!/usr/bin/env python3
"""
Fix duplicate relationship lines in PlantUML files generated by LinkML.

The LinkML gen-plantuml tool sometimes incorrectly marks relationships as
inherited (i) and creates duplicates. This script removes those duplicates.

Known duplicates that this script fixes:
- "BuildingBlock" *--> "1..*" "TemplateParameter" : "parameters"(i)
- "ConceptLibrary" *--> "0..*" "ReifiedConcept" : "concepts"(i)
- "AnalysisConcept" *--> "0..*" "ConceptOutput" : "outputs"(i)
- "AnalysisConcept" *--> "0..*" "ConceptInput" : "inputs"(i)
- "DerivationConcept" *--> "0..*" "ConceptOutput" : "outputs"(i)
- "StatisticalMethod" *--> "0..*" "ConceptOutput" : "outputs"(i)

The script works by:
1. Identifying relationship lines (with and without (i) marker)
2. Finding duplicates where both versions exist
3. Removing the version with (i) marker

Usage:
    python fix_plantuml_duplicates.py <plantuml_file>

Example:
    python fix_plantuml_duplicates.py docs/class_diagram.puml
"""

import sys
import re
from pathlib import Path


def fix_plantuml_duplicates(file_path: str) -> None:
    """
    Remove duplicate relationship lines from a PlantUML file.

    Identifies lines that appear twice where one has (i) suffix and removes
    the one with (i).

    Args:
        file_path: Path to the PlantUML file to fix
    """
    path = Path(file_path)

    if not path.exists():
        print(f"Error: File not found: {file_path}", file=sys.stderr)
        sys.exit(1)

    # Read the file
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # Track relationships to detect duplicates
    # Key: normalized relationship (without (i)), Value: line numbers
    relationships = {}
    lines_to_remove = set()

    # Pattern to match PlantUML relationships
    # Matches: "ClassA" *--> "0..*" "ClassB" : "property"
    # Or:      "ClassA" *--> "0..*" "ClassB" : "property"(i)
    relationship_pattern = re.compile(
        r'^"([^"]+)"\s+(\*?--?>|\<--?\*?)\s+"([^"]+)"\s+"([^"]+)"\s+:\s+"([^"]+)"(\(i\))?'
    )

    # First pass: identify all relationships
    for idx, line in enumerate(lines):
        match = relationship_pattern.match(line.strip())
        if match:
            source = match.group(1)
            arrow = match.group(2)
            cardinality = match.group(3)
            target = match.group(4)
            property_name = match.group(5)
            has_inherited = match.group(6) is not None

            # Create normalized key (source, arrow, target, property - without cardinality)
            # This allows matching relationships with different cardinalities
            key = f'"{source}" {arrow} "{target}" : "{property_name}"'

            if key not in relationships:
                relationships[key] = {'base': [], 'inherited': []}

            if has_inherited:
                relationships[key]['inherited'].append({'idx': idx, 'cardinality': cardinality})
            else:
                relationships[key]['base'].append({'idx': idx, 'cardinality': cardinality})

    # Second pass: mark inherited duplicates for removal
    # Remove inherited version if any non-inherited version exists for the same relationship
    for key, versions in relationships.items():
        if len(versions['base']) > 0 and len(versions['inherited']) > 0:
            # Non-inherited version(s) exist - remove all inherited versions
            for inherited in versions['inherited']:
                idx = inherited['idx']
                lines_to_remove.add(idx)
                print(f"Removing duplicate: Line {idx + 1}: {lines[idx].strip()}")

    # Third pass: write cleaned file
    if lines_to_remove:
        cleaned_lines = [line for idx, line in enumerate(lines) if idx not in lines_to_remove]

        with open(path, 'w', encoding='utf-8') as f:
            f.writelines(cleaned_lines)

        print(f"\nFixed {len(lines_to_remove)} duplicate relationship(s) in {file_path}")
    else:
        print(f"No duplicates found in {file_path}")


def main():
    if len(sys.argv) != 2:
        print("Usage: python fix_plantuml_duplicates.py <plantuml_file>")
        sys.exit(1)

    fix_plantuml_duplicates(sys.argv[1])


if __name__ == "__main__":
    main()
